### ISSUE TITLE
connection drops after 2-3 minutes of initial connection

### ISSUE THREAD

**Issue by ericpaulsen** [coder/jetbrains-coder#145]
once the connection is established, i immediately receive high latency notifications and a notice to `Update`, although it's unclear what this means. soon thereafter, the connection drops and I receive this error:

```
Code With Me

Could not reconnect to host: Failed to connect to tcp://127.0.0.1:5990#jt=412e695d-1fed-4f33-80d3-25a5d876cdd1&p=IU&fp=1B95DEEF679C09EDE7CB027E9F4EF99450ACFE17189F6C2EEB66107578C52363&cb=222.4459.24&jb=17.0.5b469.71 after all attempts
```

**Comment by Kira-Pilot** [comment]
@ericpaulsen do you have a recent reproduction?

**Comment by matifali** [comment]
Could it be dew to low memory on the host?
