### ISSUE TITLE
One-click experience to Gateway from Coder dashboard

### ISSUE THREAD

**Issue by bpmct** [coder/jetbrains-coder#149]
Coder has a "VS Code Desktop" button which does the following:

1. Open the user's VS Code
2. Install the Remote SSH extension, if not installed
3. Install the Coder Remote extension, if not installed
4. Logs in the user
5. Starts `workspace name`, if unstarted
6. Connects to `workspace name`

We'd love to add an icon for JetBrains Gateway as well, but am not sure how much the Gateway API will let us support. Some open questions:

- Do you think we should link to instructions around installing Gateway? It is less common than VS Code.
- Can we link to SSH for specific IDEs instead of requiring the dedicated gateway (e.g. SSH tab in Goland)?
  - I noticed you can still install "Coder Gateway" for Goland
- Can we link to prompt the user to install the plugin?
- Once installed, can we create links that send data to the plugin (e.g. user token, Coder URL, workspace ID?
  - I know Gateway has some query parameter support

**Comment by bpmct** [comment]
Going to remove the `blocked` label for now since it seems they claimed this is possible now.

**Comment by matifali** [comment]
Related https://github.com/coder/coder/discussions/7729
