### ISSUE TITLE
feat: authenticate to Coder from `coder_app` button but let user choose IDE

### ISSUE THREAD

**Issue by sharkymark** [coder/jetbrains-coder#317]
A Coder customer wants to use the `coder_app` to Gateway in a template but wants to give the developer freedom to select and download the IDE they want from jetbrains.com. In other words, still benefit from the 1 click authentication to the workspace.

Can our plugin somehow accomadate this or is this a Gateway limitation?

@code-asher

**Comment by code-asher** [comment]
Yup we can add this.

Cross referencing https://github.com/coder/jetbrains-coder/issues/292

**Comment by matifali** [comment]
@sharkymark Our [JetBrains-Gateway module](https://registry.coder.com/modules/jetbrains-gateway) allows specifying a list of IDEs, and then the user can choose one while creating the workspace or later from the workspace settings parameter page.

```hcl
module "jetbrains_gateway" {
  source         = "https://registry.coder.com/modules/jetbrains-gateway"
  agent_id       = coder_agent.example.id
  agent_name     = "example"
  folder         = "/home/coder/example"
  jetbrains_ides = ["GO", "WS", "IU", "IC", "PY", "PC", "PS", "CL", "RM", "DB", "RD"]
  default        = "PY"
}
```

@code-asher, Whatever you are planning to do, please try not to break our gateway module if possible. We can surely update the module if needed. Thanks.

**Comment by code-asher** [comment]
Oh that is awesome, I had not considered making it work from the module side.  Really cool!  If we do add a selector on the plugin side, it will only be used if the IDE is omitted from the link, so it will not affect the module as it currently exists.
