### ISSUE TITLE
Missing Parameter --header-command

### ISSUE THREAD

**Issue by mnebelnlb** [coder/jetbrains-coder#321]
In order to authenticate via application proxy I have to set the parameter "--header-command". Currently I must manually edit the .ssh/config before being able to use either the IntelliJ-Button or JetBrains-Gateway . This  is not very user-friendly and extremely error-prone. In Vscode this can be done by configuring the plugin before starting the connection. The Jetbrains-Gateway does not support this kind of configuration. 

I can think of two possible solutions
a.) adding another parameter to the jetbrains-gateway-link, so that I can send the correct values from the coder-button (base64 encoded as the command must contain quotes and spaces!). 
b.) a input mask to configure the plugin and set this (and other) value

Or did I miss some kind of docs? This feature was mentioned in https://github.com/coder/jetbrains-coder/releases/tag/v2.8.0

**Comment by code-asher** [comment]
There should be a setting for this under Tools > Coder.

**Comment by mnebelnlb** [comment]
<img width="985" alt="image" src="https://github.com/coder/jetbrains-coder/assets/77790399/6d87549a-9276-43fa-87e1-2e0b5fe0216e">

Found it finally! Thanks!
