### ISSUE TITLE
FEAT: Specify version

### ISSUE THREAD

**Issue by djarbz** [coder/jetbrains-coder#388]
I would like to request an option to use a specific or `latest` version of the selected IDE when the workspace is starting.

Ie: We could (optionally) specify a specific version of the IDE to launch with a special case for `latest` and when the container starts it could query the latest version to be utilized in the Gateway launcher link.

In such a case, we could pin a specific version if need be, or when a new version is released, all we would need to do is restart the workspace to update to it.

**Comment by code-asher** [comment]
It is already possible to specify the IDE version in the Gateway link.  For example:

```
jetbrains-gateway://connect#type=coder&workspace=dev&agent=coder&folder=/home/coder&url=https://dev.coder.com&token=<redacted>&ide_product_code=IU&ide_build_number=223.8836.41&ide_download_link=https://download.jetbrains.com/idea/ideaIU-2022.3.3.tar.gz"
```

We could add support for `latest`, but maybe it is better to handle that on the Coder side.

**Comment by djarbz** [comment]
I think I may have posted this on the wrong repo, I meant for the module repo.
