### ISSUE TITLE
bug: if your token expires, the 'recent' window will not update

### ISSUE THREAD

**Issue by johnstcn** [coder/jetbrains-coder#391]
Steps to reproduce:
- Put an expired token in your config
- Open Gateway
- Click on 'Coder' under 'Connections' on the left hand pane
- Observe the state
- Start or stop a workspace
- Observe that the state hasn't updated
- Go to All Providers -> Connect to Coder -> It will tell you that your token expired

**Comment by Kira-Pilot** [comment]
Bug that caused it to not update has been fixed, but still no good path to fix it.

**Comment by code-asher** [comment]
Following up with https://github.com/coder/jetbrains-coder/issues/510
