### ISSUE TITLE
Add backend monitoring process

### ISSUE THREAD

**Issue by code-asher** [coder/jetbrains-coder#392]
If the backend dies, restart it.

Should tie it to the lifetime of the client, so when the user starts the client we start monitoring, when they close the client we stop monitoring.  I think we can just use `clientLifetime` for this, but need to test to be sure.

Not 100% sure how to monitor the backend, from what I recall the remote worker has some commands for getting a backend's status, so hopefully it is straightforward.

Essentially this will be an SSH command that runs at an interval, runs the remote worker to check the backend status, and if it is dead it spawns a new one.

**Comment by Kira-Pilot** [comment]
Kira to test before we release
