### ISSUE TITLE
Add labels to workspace actions

### ISSUE THREAD

**Issue by code-asher** [coder/jetbrains-coder#436]
The play button is especially confusing in the recents window, because it looks like it could be for connecting to the workspace.

We should label it like `⏵︎Start` and the others as well, like how we have it in the dashboard.

**Comment by bcpeinhardt** [comment]
The flow is a bit weird here. Clicking the link to launch the editor as opposed to the |> button is not intuitive. In the dashboard you have to start the workspace before the button to launch an IDE is even shown, and then when it is shown it's a much larger CTA. I think that's probably what we should shoot for.

**Comment by code-asher** [comment]
Yeah it is kinda weird, clicking the link will launch SSH which will start the workspace if it is off, so technically there is no hard requirement to not let the link be clicked even if the workspace is off, but I do see how it seems weird.

It could make sense to start and connect as a single button, except that there could be many links per workspace (combinations of IDE plus directory), so there needs to be a way to determine which to launch.
