### ISSUE TITLE
Add a mechanism for keeping the IDE up to date

### ISSUE THREAD

**Issue by code-asher** [coder/jetbrains-coder#445]
Currently, once you add a connection, it will use that version of the IDE forever.

It would be convenient if you could update the IDE for that connection.  Some ideas:

- Before connecting ask "There is a newer version, do you want to update?"
- Add an "Update" button next to the IDE version.
- Could let the user choose between latest stable and latest EAP, although maybe we automatically choose based on whether the current was stable or EAP?

And as a follow-up, should it show as a new connection so you can still use the old version if you change your mind?  Or should it replace the existing connection?  Should it also delete the old IDE?  And to take that to the extreme, should we always allow only one version of each IDE per workspace?

My thinking: We should allow multiple versions if you explicitly choose different versions through the regular flow (so no change there), but from the recents screen an upgrade should replace the connection being upgraded and should delete the IDE if it is not being used for any other connections (for disk space reasons, mostly).

**Comment by Kira-Pilot** [comment]
@code-asher I like your proposal! I feel like we shouldn't automatically choose but maybe always ask the user if they want to update. Agree that unused versions should be deleted.

**Comment by code-asher** [comment]
Implemented in https://github.com/coder/jetbrains-coder/commit/43eb600127de16fd70a2d838dab4932a31164a26
