### ISSUE TITLE
IntelliJ plugin: Expose visible workspaces as a property 

### ISSUE THREAD

**Issue by kirillk** [coder/jetbrains-coder#474]
https://github.com/coryb/jetbrains-coder/blob/main/src/main/kotlin/com/coder/gateway/sdk/CoderRestClientService.kt#L107

We would like to provision this filter as a managed property for select users so they could see all the workspaces.

**Comment by matifali** [comment]
cc: @code-asher

**Comment by gtaylor** [comment]
As some extra context on usage case: VS Code currently shows all Workspaces that your permissions allow you to see (ex: as admins, we see everyone else's). We are thus able to connect to Workspaces owned by others quickly and easily from within the IDE. We'd like to be able to do the same for JB Gateway/IntelliJ.

**Comment by code-asher** [comment]
We should also make sure you can open all workspaces to which you have permissions when using `jetbrains-gateway://` URLs, since right now it will only let you connect to your own workspaces.

**Comment by code-asher** [comment]
Another consideration: the terminal link uses `/me` and will need to be changed to put the actual user.  Might be other links too.

**Comment by code-asher** [comment]
I opened another issue for the wildcard improvement.  For now, what we added works, if slowly (20 seconds for 138 off workspaces, as one data point).
