### ISSUE TITLE
Failed to retrieve IDEs: nodename nor servname provided,or not known

### ISSUE THREAD

**Issue by cdosso** [coder/jetbrains-coder#477]
Hello,

Since we upgraded coder from v2.10.3 to 2.14.2, we are unable to use gateway with coder plugin as we get the following error when we are at ide's selection step : 

coder-jetbrains--test.app--coder.XXXX.XXX--bg : nodename nor servname provided,or not known

I tried upgrading phpstorm and coder plugin but with no luck. Nothing in debug logs

Digging into plugin source code, it seems that  "coder-jetbrains--test.app--coder.XXXX.XXX--bg" should be an entry into ssh/config file but none is added. I also tried to manually add  starting and ending blocks in ssh/config and everything is wipe out, so the plugin can access and write the file.

I'm on macos Sonoma.

Thx

**Comment by thomas-dussouillez** [comment]
Hello !
I have the same problem, it's blocking all our devs since we're all working on IntelliJ.
Thanks for the help on this !

**Comment by code-asher** [comment]
Thank you for the report!  Are you accessing the IDE through the recents screen?  I think there is an issue where the SSH config is not regenerated from there, so we should make it do that.

It should regenerate properly if you add the connection again by going through the "Connect to Coder" or launching from the Coder dashboard.

If that still does not work, let me know.

**Comment by cdosso** [comment]
Hello, we already use the "Connect to coder" way. we tried resetting everything without success.

Is there anything we can enable to log what is going wrong? thankyou. 

PS: BTW your plugin was working very good before, great job!

**Comment by code-asher** [comment]
Thank you for the kind words.

If you could gather the logs from Gateway (using the cog icon in the lower left) and send them to me (either via email or you can upload them here) I will take a look and see what I can find.

**Comment by code-asher** [comment]
It is strange though, if the blocks are getting replaced (you are talking about the `# --- START CODER JETBRAINS` blocks right?) then I am not sure how the `--bg` host is being skipped, there are no conditionals in that code as far as I can see.  :thinking:

**Comment by cdosso** [comment]
error is the following : 2024-09-12 20:39:08,120 [1330103]   INFO - CoderCLIManager - No workspaces and no existing config blocks to remove

**Comment by cdosso** [comment]
Here is the error: 2024-09-12 20:39:08,120 [1330103]   INFO - CoderCLIManager - No workspaces and no existing config blocks to remove

**Comment by cdosso** [comment]
Here is the issue:

2024-09-12 20:39:08,120 [1330103]   INFO - CoderCLIManager - No workspaces and no existing config blocks to remove

related to this : https://github.com/coder/jetbrains-coder/blob/main/src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt#L324

from my understanding .ssh/config is not written so the "fake" host cannot be reached.

**Comment by cdosso** [comment]
Fun fact: old workspaces with old coder agents (2.10) are still working. Is there any BC break on agent that could explain this issue ?

**Comment by cdosso** [comment]
OMG. the issue is on our side,in workspace configuration. thank you very much for your time. sorry

**Comment by code-asher** [comment]
Glad you got it figured out!

**Comment by cdosso** [comment]
Hi, I figured out why! the issue is related to the fact that you are relying on /api/v2/templateversion/ID/resource to get workspace resources. We have conditional parameters in tf template that make some resources unavailable by default so they are not evaluated.  
Why don't you get running resources informations from /api/v2/workspace api call ?

**Comment by code-asher** [comment]
Oh interesting!

The reason we use the resource endpoint is that the API does not return resources for workspaces that are off, so when we configure SSH it would be missing all the agents from off workspaces, which could break connections in the recent connections view.

The CLI does the same thing when you run `coder config-ssh`, the plugin mimics that.

**Comment by code-asher** [comment]
I thought we only did that if the workspaces was off though.

**Comment by code-asher** [comment]
Ahh apparently we just always fetch them, but we should use the resources in the workspaces call if the workspace is running, rather than trying to fetch them from resources since we already have them.

**Comment by cdosso** [comment]
https://github.com/coder/jetbrains-coder/pull/489
