### ISSUE TITLE
Advertise the Coder plugin on the bottom of the Gateway screen

### ISSUE THREAD

**Issue by bpmct** [coder/jetbrains-coder#73]
What do we need to do to display the Coder plugin here? 

<img width="1156" alt="Screen Shot 2022-09-10 at 5 12 51 PM" src="https://user-images.githubusercontent.com/22407953/189503561-4db65318-8b9a-45c7-9f8b-c8abe2a3fc94.png">

**Comment by code-asher** [comment]
We were added in the latest EAP.
